### ISSUE TITLE
"/bin/sh: 1: /opt/conda/bin/pip: not found" in build

### ISSUE THREAD

**Issue by minertom** [DAGsHub/ml-workspace#3]
Hi, this is a straight install of  ubuntu 18.04 with Anaconda installed. The ubuntu latest docker image was installed.

Although I did not think that it would solve the problem I managed to install anaconda3 in /opt/conda. That made no difference. I expect that is because the search is inside a docker container, not outside.

"docker build  -t mymachinelearning ." Was the instruction. I have looked online and have found some suggestions such as using the ENV setting in the docker file to point to /opt/conda. That did not work.

How to proceed?

Thank You
Tom

**Comment by deanp70** [comment]
Hey Tom, sorry for not responding sooner.
I'm not sure I understand what you're trying to do and what the error is. Are you trying to rebuild the image? If so, which one?
More details would be appreciated
